version: '3.9'

services:
  client:
    build: './client'
    restart: always
    ports:
      - '3000:3000'

  server:
    build: './server'
    restart: always
    ports:
      - '3001:3000'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  