version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    hostname: mongo

  server:
    build: ./server
    restart: always
    ports:
      - '3001:3000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE=mongodb://root:example@mongo:27017
      - SESSION_SECRET=secret
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo

  client:
    build: ./client
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_data:

  
  

  