name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Environment Variables
        run: |
          echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" >> client/.env

      - name: Build Container
        run: |
          cd client
          docker build -t client:latest .

  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Environment Variables
        run: |
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> server/.env
          echo "GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}" >> server/.env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> server/.env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> server/.env
          echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> server/.env
          echo "GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }}" >> server/.env
          echo '${{ secrets.GCP_SA_KEY }}' > server/gcp-service-account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=./gcp-service-account.json" >> server/.env

      - name: Build Container
        run: |
          cd server
          docker build -t server:latest .
