name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # TODO: add build and test steps

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: Add Environment Variables
      run: |
        echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> server/.env
        echo "GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}" >> server/.env
        echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> server/.env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> server/.env
        echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> server/.env
        echo "GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }}" >> server/.env
        echo '${{ secrets.GCP_SA_KEY }}' > server/gcp-service-account.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=./gcp-service-account.json" >> server/.env
    
        echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" >> client/.env  

    - name: Push to Artifact Registry
      run: |
        mkdir -p $HOME/.docker
        echo '{"credHelpers": {"${{ secrets.GCP_REGION }}-docker.pkg.dev": "gcloud"}}' > $HOME/.docker/config.json

        cd client
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipe-app/client:latest .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipe-app/client:latest

        cd ../server
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipe-app/server:latest .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipe-app/server:latest
    
    - name: Setup Docker Containers on Compute Engine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCE_IP_ADDRESS }}
        username: ${{ secrets.GCE_USERNAME }}
        key: ${{ secrets.GCE_SSH_KEY }}
        script: |
          set -e 

          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo $ACCESS_TOKEN | docker login -u oauth2accesstoken --password-stdin ${{ secrets.GCP_REGION }}-docker.pkg.dev

          docker stop recipe-app-server || true
          docker rm recipe-app-server || true
          docker stop recipe-app-client || true
          docker rm recipe-app-client || true

          docker pull ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipe-app/client:latest
          docker pull ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipe-app/server:latest

          docker run -d --name recipe-app-client -p 3000:3000 ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipe-app/client:latest
          docker run -d --name recipe-app-server -p 3001:3000 ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipe-app/server:latest   